const bcrypt = require('bcrypt');
const readline = require('readline');

const password = 'admin_password'; // Replace with your desired admin password
const saltRounds = 10;

bcrypt.hash(password, saltRounds, (err, hash) => {
  if (err) {
    console.error(err);
  } else {
    console.log(hash);
  }
});
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('Enter admin password: ', (password) => {
  bcrypt.hash(password, saltRounds, (err, hash) => {
    if (err) {
      console.error(err);
    } else {
      console.log(`INSERT INTO users (username, password) VALUES ('admin', '${hash}');`);
    }
    rl.close();
  });
});
// INSERT INTO users (username, password) VALUES ('admin', '<password hash generated by bcrypt using /initialization/create_admin.js>');